INSERT INTO card_entity (name, suit, rank,is_played) VALUES
    ('2', 'Hearts', 2,false), ('3', 'Hearts', 3,false), ('4', 'Hearts', 4,false), ('5', 'Hearts', 5,false),
    ('6', 'Hearts', 6,false), ('7', 'Hearts', 7,false), ('8', 'Hearts', 8,false), ('9', 'Hearts', 9,false),
    ('10', 'Hearts', 10,false), ('Jack', 'Hearts', 11,false), ('Queen', 'Hearts', 12,false), ('King', 'Hearts', 13,false),
    ('Ace', 'Hearts', 14,false),
    ('2', 'Diamonds', 2,false), ('3', 'Diamonds', 3,false), ('4', 'Diamonds', 4,false), ('5', 'Diamonds', 5,false),
    ('6', 'Diamonds', 6,false), ('7', 'Diamonds', 7,false), ('8', 'Diamonds', 8,false), ('9', 'Diamonds', 9,false),
    ('10', 'Diamonds', 10,false), ('Jack', 'Diamonds', 11,false), ('Queen', 'Diamonds', 12,false), ('King', 'Diamonds', 13,false),
    ('Ace', 'Diamonds', 14,false),
    ('2', 'Clubs', 2,false), ('3', 'Clubs', 3,false), ('4', 'Clubs', 4,false), ('5', 'Clubs', 5,false),
    ('6', 'Clubs', 6,false), ('7', 'Clubs', 7,false), ('8', 'Clubs', 8,false), ('9', 'Clubs', 9,false),
    ('10', 'Clubs', 10,false), ('Jack', 'Clubs', 11,false), ('Queen', 'Clubs', 12,false), ('King', 'Clubs', 13,false),
    ('Ace', 'Clubs', 14,false),
    ('2', 'Spades', 2,false), ('3', 'Spades', 3,false), ('4', 'Spades', 4,false), ('5', 'Spades', 5,false),
    ('6', 'Spades', 6,false), ('7', 'Spades', 7,false), ('8', 'Spades', 8,false), ('9', 'Spades', 9,false),
    ('10', 'Spades', 10,false), ('Jack', 'Spades', 11,false), ('Queen', 'Spades', 12,false), ('King', 'Spades', 13,false),
    ('Ace', 'Spades', 14,false);
